### ISSUE TITLE
Console Error on server 

### ISSUE THREAD

**Issue by thororen1234** [Globox1997/PartyAddon#5]
### Minecraft Version

1.19.x

### Mod Loader Version

0.14.22

### Mod Version

1.0.3

### Describe the Issue

Don't know exactly why this happens but hud disappears, the exp stops getting shared, and then the server console logs [Server thread/ERROR]: Error executing task on Server java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1 which is in the log many times

### latest.log

[latest.log](https://github.com/Globox1997/PartyAddon/files/12641062/latest.log)

### Do you use any other mods except the required ones?

Yes this does still happen

**Comment by RunAge** [comment]
same on 1.20.1
```
aged-aqua-aged-1  | java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
aged-aqua-aged-1  |     at jdk.internal.util.Preconditions.outOfBounds(Unknown Source) ~[?:?]
aged-aqua-aged-1  |     at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source) ~[?:?]
aged-aqua-aged-1  |     at jdk.internal.util.Preconditions.checkIndex(Unknown Source) ~[?:?]
aged-aqua-aged-1  |     at java.util.Objects.checkIndex(Unknown Source) ~[?:?]
aged-aqua-aged-1  |     at java.util.ArrayList.get(Unknown Source) ~[?:?]
aged-aqua-aged-1  |     at net.partyaddon.network.PartyAddonServerPacket.writeS2CMapCompatPacket(PartyAddonServerPacket.java:219) ~[partyaddon-1.0.4.jar:?]
aged-aqua-aged-1  |     at net.partyaddon.network.PartyAddonServerPacket.lambda$init$14(PartyAddonServerPacket.java:121) ~[partyaddon-1.0.4.jar:?]
aged-aqua-aged-1  |     at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
aged-aqua-aged-1  |     at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
aged-aqua-aged-1  |     at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
aged-aqua-aged-1  |     at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[server-intermediary.jar:?]
aged-aqua-aged-1  |     at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[server-intermediary.jar:?]
aged-aqua-aged-1  |     at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
aged-aqua-aged-1  |     at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[server-intermediary.jar:?]
aged-aqua-aged-1  |     at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[server-intermediary.jar:?]
aged-aqua-aged-1  |     at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[server-intermediary.jar:?]
aged-aqua-aged-1  |     at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742) ~[server-intermediary.jar:?]
aged-aqua-aged-1  |     at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[server-intermediary.jar:?]
aged-aqua-aged-1  |     at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
aged-aqua-aged-1  |     at java.lang.Thread.run(Unknown Source) ~[?:?]
```

**Comment by Hurokun** [comment]
still happening, i had this happen 42 times in a roll and then get a warning that the server was getting overloaded.
```
[06:47:57] [Server thread/ERROR]: Error executing task on Server
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at net.partyaddon.network.PartyAddonServerPacket.writeS2CMapCompatPacket(PartyAddonServerPacket.java:219) ~[partyaddon-1.0.4.jar:?]
	at net.partyaddon.network.PartyAddonServerPacket.lambda$init$14(PartyAddonServerPacket.java:121) ~[partyaddon-1.0.4.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

`
[06:47:58] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2114ms or 42 ticks behind
`

**Comment by candied-apple** [comment]
Please fix this still happens

**Comment by candied-apple** [comment]
Please fix this still happens @Globox1997

**Comment by candied-apple** [comment]
https://github.com/Globox1997/PartyAddon/pull/9
